language: java
jdk:
- oraclejdk8
install: mvn clean install -P-quality-checks -DskipTests
script:
- mvn install
after_success:
- if [ $TRAVIS_BRANCH == 'master' ]; then mvn heroku:deploy -Dheroku.appName=morning-stream-2444
  -Pheroku; fi
after_script:
- mvn site site:deploy
env:
  global:
  - secure: XjWKNKwJPD9sjTxlX4ClGwoQO2P2W4V5I1B4Tkp2413wgudj1insT57H0smZ7xCpTCBkdCzLGBzm7Jwrsk+8WI2fZYVUMTMzH9g58y0t7upu+j8jpe+1FGYTW04ylgAa+utNDDbcI9ZbSlvqgm0z/Hhehy/ZrAVtmpL1FszS4TRJ+3EYy8qOA0zloVvC8iGz3wUn7KfvD84CBgS3q8uLb5unZJDN3i8YpY01pm8Z0UrhMyr+76sWTJNF7BXHfIXbxkvY9aXhQV93vnWpTHsxLaU7uIaf0+VI0V9BPuKCpd73y0WfjE1YQi/Z9RNQfCjepre+EeNlekRh2W9j/sYv9sW8HsBa68Ng0LE8Jl2n6NjBcWRP/9xcFr7geapsLU6LJuJlHTpxTb+uhSj1yZeZyEwboyB8eCwTR2Bk/BhnWPDXOvU17KCK/LmYq8CI8NYLO+vPN1KrAh/9rq27A++boe1wqb5guWRJ/sdLHaG58FbEDV5ExtFjlmkf+xyvOEvKa2d85mJ+70d95OTQ8TMVoHuT1da0nPquQqzW+t37wm3g7WyQhniMOthrSPUJMLehBmv6cr8bImZmhq4baMZ+FKNKGBM0bj3DGBmcEoZEqYf/Dlh4Br7rrHjacGDw/zMd3BeUsdrWlwx3ILJP9u7s6gcYVMRTXhG41K9dVFIQ5UE=
  - secure: fb80dB8fUoHHcLAFn4L6iQBdIEpKzolcv7ewzHUpEHMfml1MRKyqpYwJ/OSR4Z5YNvJjTcKHvLs4aSFb/po3sxy2EYySz4CsZ68vOl6BOP8mxrQltHeSGcuq30Skmpu4aQtu5cDXsSbpIyrgLoxN+xCzTTRGc8NStfuQcAu0K7sfrwIVLUPHU0tFV2T+yFEKDqq0x8C91Gxe864iWeycZs9M7/yc+5tc1ydtTk5CegjYFC5tf2dbfboprUveR/5kzuXrwM3lnsNBYvg8omHXvmkZGCQtQAIBgz6g7OAmwNtDpuP0SxIPqsmyhn3l8sgNHeWw9AxWpwa8UMCaQhatA9Mib/RIMPjfJpJR0GaFEiOToQIXd4+f8kupRJJlhvX6UzpxXUMKDbH+CEcRKQMF3XH1D4Dgz/tSz/p5igSQqU/SJQe5js9VntNlIZupP5JJeBodkF4XomkM4sZhpWlvt+zEW1zAHNFL+O+jsRga4QVOdULy23zlsG02ey2yvQ95ja1/FjRxDF+mKG7Q97e+lkpBfOEJ3mVEOYBx+SfuA9DyucUGE7Po++91YZirx0OF3cOEiLV1zR+KZRN1LOINW9En5eRRWh5F4Nbktv9U3Z4yThN/SRhJA+OdiJLy8J+oIKszz9bdDItjOTVboveFMl7nBLo3Y7e47wn0fWuYR6I=
