language: java
jdk:
- oraclejdk8
install: mvn clean install -P-quality-checks -DskipTests
script:
- mvn install
after_script: 
- mvn site site:deploy
- mvn heroku:deploy -Dheroku.appName=morning-stream-2444 -Pheroku
env:
  global:
    secure: XjWKNKwJPD9sjTxlX4ClGwoQO2P2W4V5I1B4Tkp2413wgudj1insT57H0smZ7xCpTCBkdCzLGBzm7Jwrsk+8WI2fZYVUMTMzH9g58y0t7upu+j8jpe+1FGYTW04ylgAa+utNDDbcI9ZbSlvqgm0z/Hhehy/ZrAVtmpL1FszS4TRJ+3EYy8qOA0zloVvC8iGz3wUn7KfvD84CBgS3q8uLb5unZJDN3i8YpY01pm8Z0UrhMyr+76sWTJNF7BXHfIXbxkvY9aXhQV93vnWpTHsxLaU7uIaf0+VI0V9BPuKCpd73y0WfjE1YQi/Z9RNQfCjepre+EeNlekRh2W9j/sYv9sW8HsBa68Ng0LE8Jl2n6NjBcWRP/9xcFr7geapsLU6LJuJlHTpxTb+uhSj1yZeZyEwboyB8eCwTR2Bk/BhnWPDXOvU17KCK/LmYq8CI8NYLO+vPN1KrAh/9rq27A++boe1wqb5guWRJ/sdLHaG58FbEDV5ExtFjlmkf+xyvOEvKa2d85mJ+70d95OTQ8TMVoHuT1da0nPquQqzW+t37wm3g7WyQhniMOthrSPUJMLehBmv6cr8bImZmhq4baMZ+FKNKGBM0bj3DGBmcEoZEqYf/Dlh4Br7rrHjacGDw/zMd3BeUsdrWlwx3ILJP9u7s6gcYVMRTXhG41K9dVFIQ5UE=
